//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebManuals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manuals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public manuals()
        {
            this.manual_groups = new HashSet<manual_groups>();
        }
    
        public int manualid { get; set; }
        public string manual_name { get; set; }
        public Nullable<int> manual_languageid { get; set; }
        public Nullable<int> manual_modeltypeid { get; set; }
        public string manual_url { get; set; }
        public byte[] manual_content { get; set; }
        public string manual_master_model { get; set; }
    
        public virtual languages languages { get; set; }
        public virtual modeltypes modeltypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<manual_groups> manual_groups { get; set; }
    }
}
