//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebManuals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manual_groups
    {
        public int manual_groupid { get; set; }
        public Nullable<int> languageid { get; set; }
        public Nullable<int> modeltypeid { get; set; }
        public Nullable<int> manualid { get; set; }
        public string manual_group_name { get; set; }
    
        public virtual manuals manuals { get; set; }
        public virtual languages languages { get; set; }
        public virtual modeltypes modeltypes { get; set; }
    }
}
