//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebManuals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class revisions
    {
        public int revisionid { get; set; }
        public byte[] revision_date { get; set; }
        public Nullable<int> manualid { get; set; }
        public Nullable<int> digitalid { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
