//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebManuals.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webmanualsEntities : DbContext
    {
        public webmanualsEntities()
            : base("name=webmanualsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<languages> languages { get; set; }
        public virtual DbSet<manuals> manuals { get; set; }
        public virtual DbSet<modeltypes> modeltypes { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<manual_groups> manual_groups { get; set; }
        public virtual DbSet<revisions> revisions { get; set; }
        public virtual DbSet<ipinfo> ipinfo { get; set; }
    }
}
